name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    services:
      crdb:
        image: cockroachdb/cockroach
        env:
          COCKROACH_ARGS: "start-single-node --insecure"
        ports:
          - 26257:26257
        options: >-
          --health-cmd "curl -f http://localhost:8080/health?ready=1"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Run migrations
      - run: pnpm --filter api exec mikro-orm migration:up
        env:
          DATABASE_URL: "cockroachdb://root@localhost:26257/defaultdb?sslmode=disable"

      # Run tests, build, and check linting
      - run: pnpm exec nx affected -t lint:ci test build
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
          DATABASE_URL: "cockroachdb://root@localhost:26257/defaultdb?sslmode=disable"

  build-image:
    name: 'Build images'
    uses: ./.github/workflows/oci-build-image.yml
    if: github.event_name != 'pull_request'
    needs: test
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: sageleaf-api
            target: api
          - image_name: sageleaf-frontend
            target: frontend
    with:
      registry: ghcr.io/caj2
      image_name: ${{ matrix.image_name }}
      target: ${{ matrix.target }}
