name: CI

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  nx-affected:
    name: 'Calculate affected projects'
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.affected.outputs.affected }}
      e2e-affected: ${{ steps.affected.outputs.e2e-affected }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      - name: 'Calculate affected projects'
        id: affected
        run: |
          echo "affected=$(pnpm exec nx show projects --affected --with-target build --sep ',')" >> $GITHUB_OUTPUT
          echo "e2e-affected=$(pnpm exec nx show projects --affected --with-target e2e:ci --sep ',')" >> $GITHUB_OUTPUT

  test:
    name: 'Build & Test API + Frontend'
    runs-on: ubuntu-latest
    if: ${{ contains(needs.nx-affected.outputs.affected, '@sageleaf/api') }}
    needs: nx-affected
    timeout-minutes: 20
    services:
      crdb:
        image: cockroachdb/cockroach
        env:
          COCKROACH_ARGS: 'start-single-node --insecure --store=type=mem,size=0.25 --advertise-addr=localhost'
        ports:
          - 26257:26257
        options: >-
          --health-cmd "curl -f http://localhost:8080/health?ready=1"
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Check linting
      - run: pnpm exec nx affected -t lint:ci
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_WRITE }}

      # Build
      - run: pnpm exec nx affected -t build
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_WRITE }}
          POSTHOG_PERSONAL_API_KEY: ${{ secrets.POSTHOG_PERSONAL_API_KEY }}
          DATABASE_URL: 'cockroachdb://root@localhost:26257/defaultdb?sslmode=disable'

      # Run migrations
      - run: pnpm --filter api exec mikro-orm migration:up
        env:
          DATABASE_URL: 'cockroachdb://root@localhost:26257/defaultdb?sslmode=disable'

      # Run tests
      - run: pnpm exec nx affected -t test
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_WRITE }}
          NODE_ENV: test
          TEST_DATABASE_URL: 'cockroachdb://root@localhost:26257/defaultdb?sslmode=disable'

      - run: pnpm --filter=@sageleaf/e2e-frontend exec playwright install --with-deps
        if: contains(needs.nx-affected.outputs.e2e-affected, '@sageleaf/e2e-frontend')
      - run: pnpm exec nx affected -t e2e:ci
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_WRITE }}
          NODE_ENV: test

  test-frontend:
    name: 'Build & Test Frontend'
    runs-on: ubuntu-latest
    if: ${{ !contains(needs.nx-affected.outputs.affected, '@sageleaf/api') }}
    needs: nx-affected
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Check linting
      - run: pnpm exec nx affected -t lint:ci
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_WRITE }}

      # Build
      - run: pnpm exec nx affected -t build
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_WRITE }}
          POSTHOG_PERSONAL_API_KEY: ${{ secrets.POSTHOG_PERSONAL_API_KEY }}

      # Run tests
      - run: pnpm exec nx affected -t test
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_WRITE }}
          NODE_ENV: test

      - run: pnpm --filter=@sageleaf/e2e-frontend exec playwright install --with-deps
        if: contains(needs.nx-affected.outputs.e2e-affected, '@sageleaf/e2e-frontend')
      - run: pnpm exec nx affected -t e2e:ci
        env:
          NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_WRITE }}
          NODE_ENV: test

  build-image-api:
    name: 'Build API images'
    uses: ./.github/workflows/oci-build-image.yml
    if: ${{ contains(needs.nx-affected.outputs.affected, '@sageleaf/api') }}
    needs: [nx-affected, test]
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    with:
      registry: ghcr.io/caj2
      image_name: sageleaf-api
      target: api

  build-image-frontend:
    name: 'Build frontend images'
    uses: ./.github/workflows/oci-build-image.yml
    if: ${{ !failure() && !cancelled() && contains(needs.nx-affected.outputs.affected, '@sageleaf/frontend') }}
    needs: [nx-affected, test, test-frontend]
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    with:
      registry: ghcr.io/caj2
      image_name: sageleaf-frontend
      target: frontend

  build-image-science:
    name: 'Build science images'
    uses: ./.github/workflows/oci-build-image.yml
    if: ${{ !failure() && !cancelled() && contains(needs.nx-affected.outputs.affected, '@sageleaf/science') }}
    needs: [nx-affected, test, test-frontend]
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    with:
      registry: ghcr.io/caj2
      image_name: sageleaf-science
      target: science
